    var norra2_json = [
        {
            "fastighetsbeteckning": "Stora Sj\u00f6fallet 1",
            "developer": "Bonava",
            "phase": "Norra 2",
            "stage": "In operation",
            "no_of_appartments": 64,
            "atemp_m2": 6794,
            "national_legislation_bbr": 90,
            "requirement_level_kwhm2_atemp": 55,
            "total_energy_use_in_operation": null,
            "heating_district_heating_in_operation": null,
            "heating_electricity_in_operation": null,
            "hot_water_district_heating_in_operation": null,
            "hot_water_electricity_in_operation": null,
            "property_electricity_in_operation": null,
            "locally_generated_electricity_in_operation": null,
            "locally_generated_heating_in_operation": null,
            "total_energy_use_construction": 53,
            "heating_district_heating_construction": 32.3,
            "heating_electricity_construction": 0,
            "hot_water_district_heating_construction": 15,
            "hot_water_electricity_construction": 0,
            "property_electricity_construction": 14.299999999999999,
            "locally_generated_electricity_construction": 3.6,
            "locally_generated_heating_construction": 0,
            "regionally_generated_energy_construction": 0,
            "total_energy_use_design": 60,
            "heating_district_geating_design": 20,
            "heating_electricity_design": 0,
            "hot_water_district_heating_design": 20,
            "hot_water_electricity_design": 0,
            "property_electricity_design": 10,
            "locally_generated_electricity_design": 10,
            "locally_generated_heating_design": 0,
            "co2_emissions_tonnes": 26.296244939999994,
            "requirment_level_gsi": 0.6,
            "green_space_index_gsi_in_operation": 0.6,
            "green_space_index_gsi_construction": 0.61,
            "green_space_index_gsi_design": 0.62,
            "green_courtyard_m2": 390.5,
            "green_roofs_m2": 550,
            "requirement_bicycle_parkingapartment": 2.2,
            "bicycle_parking_spacesapartment": 2.38,
            "no._bicycle_parkingspace": 152,
            "requirment_car_parkingapartment": 0.5,
            "car_parking_spacesapartment": 0.59,
            "no._of_car_parkingspace": 38,
            "requiremant_electrical_chargning_points": null,
            "chare_of_electrical_charging_points": 26,
            "no._of_electrical_charing_points": 10,
            "requirement_construction_waste_kgm2_gfa": 20,
            "construction_waste_kgm2_gfa": 38.11,
            "requirement_distance_to_vwc_m": 30,
            "distance_to_vwc_m": 30,
            "requirement_distance_to_recycling_room_m": 50,
            "distance_to_recycling_room_m": 30,
            "recycling_room_in_property": "yes",
            "requirement_materials": "All materials are controlled in an environmental assesment system",
            "building_material_assessment_system_yes_or_no": "yes",
            "number_of_deveations": 5,
            "requirements_indoor_environment": "Gold",
            "indoor_environment": "Silver"
        },
        {
            "fastighetsbeteckning": "Stora Sj\u00f6fallet 4",
            "developer": "SSM",
            "phase": "Norra 2",
            "stage": "In operation",
            "no_of_appartments": 46,
            "atemp_m2": 2523,
            "national_legislation_bbr": 90,
            "requirement_level_kwhm2_atemp": 55,
            "total_energy_use_in_operation": 38.94,
            "heating_district_heating_in_operation": 9.99,
            "heating_electricity_in_operation": 0,
            "hot_water_district_heating_in_operation": 25.06,
            "hot_water_electricity_in_operation": 0,
            "property_electricity_in_operation": 8.64,
            "locally_generated_electricity_in_operation": 4.75,
            "locally_generated_heating_in_operation": 0,
            "total_energy_use_construction": 54,
            "heating_district_heating_construction": 14,
            "heating_electricity_construction": 0,
            "hot_water_district_heating_construction": 25,
            "hot_water_electricity_construction": 0,
            "property_electricity_construction": 17,
            "locally_generated_electricity_construction": 2,
            "locally_generated_heating_construction": 0,
            "regionally_generated_energy_construction": 0,
            "total_energy_use_design": 60,
            "heating_district_geating_design": 20,
            "heating_electricity_design": 0,
            "hot_water_district_heating_design": 20,
            "hot_water_electricity_design": 0,
            "property_electricity_design": 10,
            "locally_generated_electricity_design": 10,
            "locally_generated_heating_design": 0,
            "co2_emissions_tonnes": 6.595275902999999,
            "requirment_level_gsi": 0.6,
            "green_space_index_gsi_in_operation": 0.6,
            "green_space_index_gsi_construction": 0.61,
            "green_space_index_gsi_design": 0.62,
            "green_courtyard_m2": 390.5,
            "green_roofs_m2": 950,
            "requirement_bicycle_parkingapartment": 2.2,
            "bicycle_parking_spacesapartment": 2.52,
            "no._bicycle_parkingspace": 116,
            "requirment_car_parkingapartment": 0.5,
            "car_parking_spacesapartment": 0.24,
            "no._of_car_parkingspace": 11,
            "requiremant_electrical_chargning_points": null,
            "chare_of_electrical_charging_points": 9,
            "no._of_electrical_charing_points": 1,
            "requirement_construction_waste_kgm2_gfa": 20,
            "construction_waste_kgm2_gfa": 43.6,
            "requirement_distance_to_vwc_m": 30,
            "distance_to_vwc_m": 0,
            "requirement_distance_to_recycling_room_m": 50,
            "distance_to_recycling_room_m": 0,
            "recycling_room_in_property": "yes",
            "requirement_materials": "All materials are controlled in an environmental assesment system",
            "building_material_assessment_system_yes_or_no": "yes",
            "number_of_deveations": 5,
            "requirements_indoor_environment": "Gold",
            "indoor_environment": "Gold"
        },
        {
            "fastighetsbeteckning": "Stora Sj\u00f6fallet 2",
            "developer": "Viktor Hanson",
            "phase": "Norra 2",
            "stage": "In operation",
            "no_of_appartments": 30,
            "atemp_m2": 3681,
            "national_legislation_bbr": 90,
            "requirement_level_kwhm2_atemp": 55,
            "total_energy_use_in_operation": 71.8,
            "heating_district_heating_in_operation": 44.4,
            "heating_electricity_in_operation": 0,
            "hot_water_district_heating_in_operation": 22.4,
            "hot_water_electricity_in_operation": 0,
            "property_electricity_in_operation": 12.5,
            "locally_generated_electricity_in_operation": 3,
            "locally_generated_heating_in_operation": 4.5,
            "total_energy_use_construction": 54.79999999999999,
            "heating_district_heating_construction": 31.099999999999998,
            "heating_electricity_construction": 0,
            "hot_water_district_heating_construction": 20.5,
            "hot_water_electricity_construction": 0,
            "property_electricity_construction": 10.9,
            "locally_generated_electricity_construction": 4.5,
            "locally_generated_heating_construction": 3.2,
            "regionally_generated_energy_construction": 0,
            "total_energy_use_design": 60,
            "heating_district_geating_design": 20,
            "heating_electricity_design": 0,
            "hot_water_district_heating_design": 20,
            "hot_water_electricity_design": 0,
            "property_electricity_design": 10,
            "locally_generated_electricity_design": 10,
            "locally_generated_heating_design": 0,
            "co2_emissions_tonnes": 17.70203943,
            "requirment_level_gsi": 0.6,
            "green_space_index_gsi_in_operation": 0.6,
            "green_space_index_gsi_construction": 0.61,
            "green_space_index_gsi_design": 0.62,
            "green_courtyard_m2": 390.5,
            "green_roofs_m2": 250,
            "requirement_bicycle_parkingapartment": 2.2,
            "bicycle_parking_spacesapartment": 2.47,
            "no._bicycle_parkingspace": 74,
            "requirment_car_parkingapartment": 0.5,
            "car_parking_spacesapartment": 0.67,
            "no._of_car_parkingspace": 20,
            "requiremant_electrical_chargning_points": null,
            "chare_of_electrical_charging_points": 15,
            "no._of_electrical_charing_points": 3,
            "requirement_construction_waste_kgm2_gfa": 20,
            "construction_waste_kgm2_gfa": 35.04,
            "requirement_distance_to_vwc_m": 30,
            "distance_to_vwc_m": 5,
            "requirement_distance_to_recycling_room_m": 50,
            "distance_to_recycling_room_m": 0,
            "recycling_room_in_property": "yes",
            "requirement_materials": "All materials are controlled in an environmental assesment system",
            "building_material_assessment_system_yes_or_no": "yes",
            "number_of_deveations": 5,
            "requirements_indoor_environment": "Gold",
            "indoor_environment": "Gold"
        },
        {
            "fastighetsbeteckning": "Stora Sj\u00f6fallet 3",
            "developer": "Wallenstam",
            "phase": "Norra 2",
            "stage": "In operation",
            "no_of_appartments": 127,
            "atemp_m2": 8776,
            "national_legislation_bbr": 90,
            "requirement_level_kwhm2_atemp": 55,
            "total_energy_use_in_operation": 85.39999999999999,
            "heating_district_heating_in_operation": 57.9,
            "heating_electricity_in_operation": 0,
            "hot_water_district_heating_in_operation": 19.4,
            "hot_water_electricity_in_operation": 0,
            "property_electricity_in_operation": 8.1,
            "locally_generated_electricity_in_operation": 0,
            "locally_generated_heating_in_operation": 0,
            "total_energy_use_construction": 54.9,
            "heating_district_heating_construction": 24.9,
            "heating_electricity_construction": 0,
            "hot_water_district_heating_construction": 18.5,
            "hot_water_electricity_construction": 0,
            "property_electricity_construction": 13.5,
            "locally_generated_electricity_construction": 0,
            "locally_generated_heating_construction": 0,
            "regionally_generated_energy_construction": 2,
            "total_energy_use_design": 60,
            "heating_district_geating_design": 20,
            "heating_electricity_design": 0,
            "hot_water_district_heating_design": 20,
            "hot_water_electricity_design": 0,
            "property_electricity_design": 10,
            "locally_generated_electricity_design": 10,
            "locally_generated_heating_design": 0,
            "co2_emissions_tonnes": 50.33009671999999,
            "requirment_level_gsi": 0.6,
            "green_space_index_gsi_in_operation": 0.6,
            "green_space_index_gsi_construction": 0.61,
            "green_space_index_gsi_design": 0.62,
            "green_courtyard_m2": 390.5,
            "green_roofs_m2": 1700,
            "requirement_bicycle_parkingapartment": 2.2,
            "bicycle_parking_spacesapartment": 2.11,
            "no._bicycle_parkingspace": 268,
            "requirment_car_parkingapartment": 0.5,
            "car_parking_spacesapartment": 0.39,
            "no._of_car_parkingspace": 49,
            "requiremant_electrical_chargning_points": null,
            "chare_of_electrical_charging_points": 12,
            "no._of_electrical_charing_points": 6,
            "requirement_construction_waste_kgm2_gfa": 20,
            "construction_waste_kgm2_gfa": 46.26,
            "requirement_distance_to_vwc_m": 30,
            "distance_to_vwc_m": 40,
            "requirement_distance_to_recycling_room_m": 50,
            "distance_to_recycling_room_m": 45,
            "recycling_room_in_property": "yes",
            "requirement_materials": "All materials are controlled in an environmental assesment system",
            "building_material_assessment_system_yes_or_no": "yes",
            "number_of_deveations": 5,
            "requirements_indoor_environment": "Gold",
            "indoor_environment": "Gold"
        },
        {
            "fastighetsbeteckning": "Domarudden 2",
            "developer": "Wallenstam f\u00f6rskola",
            "phase": "Norra 2",
            "stage": "In operation",
            "no_of_appartments": 0,
            "atemp_m2": 816,
            "national_legislation_bbr": 98,
            "requirement_level_kwhm2_atemp": 64,
            "total_energy_use_in_operation": 97.93,
            "heating_district_heating_in_operation": 79.4,
            "heating_electricity_in_operation": 0,
            "hot_water_district_heating_in_operation": 2.63,
            "hot_water_electricity_in_operation": 0,
            "property_electricity_in_operation": 15.9,
            "locally_generated_electricity_in_operation": 0,
            "locally_generated_heating_in_operation": 0,
            "total_energy_use_construction": 64,
            "heating_district_heating_construction": 43,
            "heating_electricity_construction": 0,
            "hot_water_district_heating_construction": 5,
            "hot_water_electricity_construction": 0,
            "property_electricity_construction": 16,
            "locally_generated_electricity_construction": 0,
            "locally_generated_heating_construction": 0,
            "regionally_generated_energy_construction": 0,
            "total_energy_use_design": 60,
            "heating_district_geating_design": 20,
            "heating_electricity_design": 0,
            "hot_water_district_heating_design": 20,
            "hot_water_electricity_design": 0,
            "property_electricity_design": 10,
            "locally_generated_electricity_design": 10,
            "locally_generated_heating_design": 0,
            "co2_emissions_tonnes": 5.340995807999999,
            "requirment_level_gsi": 0.6,
            "green_space_index_gsi_in_operation": 0,
            "green_space_index_gsi_construction": 0,
            "green_space_index_gsi_design": 0,
            "green_courtyard_m2": 0,
            "green_roofs_m2": 0,
            "requirement_bicycle_parkingapartment": 2.2,
            "bicycle_parking_spacesapartment": "NA",
            "no._bicycle_parkingspace": 5,
            "requirment_car_parkingapartment": 0.5,
            "car_parking_spacesapartment": "NA",
            "no._of_car_parkingspace": 0,
            "requiremant_electrical_chargning_points": null,
            "chare_of_electrical_charging_points": 0,
            "no._of_electrical_charing_points": 0,
            "requirement_construction_waste_kgm2_gfa": 20,
            "construction_waste_kgm2_gfa": 81,
            "requirement_distance_to_vwc_m": 30,
            "distance_to_vwc_m": 4,
            "requirement_distance_to_recycling_room_m": 50,
            "distance_to_recycling_room_m": 4,
            "recycling_room_in_property": "yes",
            "requirement_materials": "All materials are controlled in an environmental assesment system",
            "building_material_assessment_system_yes_or_no": "yes",
            "number_of_deveations": 5,
            "requirements_indoor_environment": "Gold",
            "indoor_environment": "Gold"
        },
        {
            "fastighetsbeteckning": "Hornslandet 1",
            "developer": "Stockholmshem",
            "phase": "Norra 2",
            "stage": "In operation",
            "no_of_appartments": 159,
            "atemp_m2": 19210,
            "national_legislation_bbr": 90,
            "requirement_level_kwhm2_atemp": 55,
            "total_energy_use_in_operation": 68.8,
            "heating_district_heating_in_operation": 46,
            "heating_electricity_in_operation": 0,
            "hot_water_district_heating_in_operation": 15.5,
            "hot_water_electricity_in_operation": 0,
            "property_electricity_in_operation": 11.3,
            "locally_generated_electricity_in_operation": 4,
            "locally_generated_heating_in_operation": 0,
            "total_energy_use_construction": 53,
            "heating_district_heating_construction": 24.6,
            "heating_electricity_construction": 0,
            "hot_water_district_heating_construction": 22,
            "hot_water_electricity_construction": 0,
            "property_electricity_construction": 9.899999999999999,
            "locally_generated_electricity_construction": 4.1,
            "locally_generated_heating_construction": 0,
            "regionally_generated_energy_construction": 0,
            "total_energy_use_design": 60,
            "heating_district_geating_design": 20,
            "heating_electricity_design": 0,
            "hot_water_district_heating_design": 20,
            "hot_water_electricity_design": 0,
            "property_electricity_design": 10,
            "locally_generated_electricity_design": 10,
            "locally_generated_heating_design": 0,
            "co2_emissions_tonnes": 88.68430969999999,
            "requirment_level_gsi": 0.6,
            "green_space_index_gsi_in_operation": 0.62,
            "green_space_index_gsi_construction": 0.67,
            "green_space_index_gsi_design": 0.68,
            "green_courtyard_m2": 1600,
            "green_roofs_m2": 2050,
            "requirement_bicycle_parkingapartment": 2.2,
            "bicycle_parking_spacesapartment": 2.34,
            "no._bicycle_parkingspace": 139,
            "requirment_car_parkingapartment": 0.5,
            "car_parking_spacesapartment": 0.5,
            "no._of_car_parkingspace": 80,
            "requiremant_electrical_chargning_points": null,
            "chare_of_electrical_charging_points": 11,
            "no._of_electrical_charing_points": 4,
            "requirement_construction_waste_kgm2_gfa": 20,
            "construction_waste_kgm2_gfa": 37.14,
            "requirement_distance_to_vwc_m": 30,
            "distance_to_vwc_m": 39,
            "requirement_distance_to_recycling_room_m": 50,
            "distance_to_recycling_room_m": 84,
            "recycling_room_in_property": "yes",
            "requirement_materials": "All materials are controlled in an environmental assesment system",
            "building_material_assessment_system_yes_or_no": "yes",
            "number_of_deveations": 5,
            "requirements_indoor_environment": "Gold",
            "indoor_environment": "Gold"
        },
        {
            "fastighetsbeteckning": "Sonfj\u00e4llet 3",
            "developer": "Erik Wallin",
            "phase": "Norra 2",
            "stage": "In operation",
            "no_of_appartments": 18,
            "atemp_m2": 3525,
            "national_legislation_bbr": 90,
            "requirement_level_kwhm2_atemp": 55,
            "total_energy_use_in_operation": null,
            "heating_district_heating_in_operation": null,
            "heating_electricity_in_operation": null,
            "hot_water_district_heating_in_operation": null,
            "hot_water_electricity_in_operation": null,
            "property_electricity_in_operation": null,
            "locally_generated_electricity_in_operation": null,
            "locally_generated_heating_in_operation": null,
            "total_energy_use_construction": 47,
            "heating_district_heating_construction": 21.7,
            "heating_electricity_construction": 0,
            "hot_water_district_heating_construction": 26.3,
            "hot_water_electricity_construction": 0,
            "property_electricity_construction": 9.8,
            "locally_generated_electricity_construction": 2.5,
            "locally_generated_heating_construction": 6.5,
            "regionally_generated_energy_construction": 0,
            "total_energy_use_design": 60,
            "heating_district_geating_design": 20,
            "heating_electricity_design": 0,
            "hot_water_district_heating_design": 20,
            "hot_water_electricity_design": 0,
            "property_electricity_design": 10,
            "locally_generated_electricity_design": 10,
            "locally_generated_heating_design": 0,
            "co2_emissions_tonnes": 11.507609249999998,
            "requirment_level_gsi": 0.6,
            "green_space_index_gsi_in_operation": 0.6,
            "green_space_index_gsi_construction": 0.64,
            "green_space_index_gsi_design": 0.6,
            "green_courtyard_m2": 409,
            "green_roofs_m2": 350,
            "requirement_bicycle_parkingapartment": 2.2,
            "bicycle_parking_spacesapartment": 2.22,
            "no._bicycle_parkingspace": 40,
            "requirment_car_parkingapartment": 0.5,
            "car_parking_spacesapartment": 1,
            "no._of_car_parkingspace": 18,
            "requiremant_electrical_chargning_points": null,
            "chare_of_electrical_charging_points": 44,
            "no._of_electrical_charing_points": 8,
            "requirement_construction_waste_kgm2_gfa": 20,
            "construction_waste_kgm2_gfa": 45.47,
            "requirement_distance_to_vwc_m": 30,
            "distance_to_vwc_m": 40.7,
            "requirement_distance_to_recycling_room_m": 50,
            "distance_to_recycling_room_m": 41,
            "recycling_room_in_property": "yes",
            "requirement_materials": "All materials are controlled in an environmental assesment system",
            "building_material_assessment_system_yes_or_no": "yes",
            "number_of_deveations": 5,
            "requirements_indoor_environment": "Gold",
            "indoor_environment": "Gold"
        },
        {
            "fastighetsbeteckning": "Sonfj\u00e4llet 1",
            "developer": "HEBA",
            "phase": "Norra 2",
            "stage": "In operation",
            "no_of_appartments": 72,
            "atemp_m2": 7863,
            "national_legislation_bbr": 90,
            "requirement_level_kwhm2_atemp": 55,
            "total_energy_use_in_operation": 62.2,
            "heating_district_heating_in_operation": 35.9,
            "heating_electricity_in_operation": 0,
            "hot_water_district_heating_in_operation": 19.4,
            "hot_water_electricity_in_operation": 0,
            "property_electricity_in_operation": 9.100000000000001,
            "locally_generated_electricity_in_operation": 2.2,
            "locally_generated_heating_in_operation": 0,
            "total_energy_use_construction": 51.5,
            "heating_district_heating_construction": 28.3,
            "heating_electricity_construction": 0,
            "hot_water_district_heating_construction": 17,
            "hot_water_electricity_construction": 0,
            "property_electricity_construction": 9.1,
            "locally_generated_electricity_construction": 2.9,
            "locally_generated_heating_construction": 0,
            "regionally_generated_energy_construction": 0,
            "total_energy_use_design": 60,
            "heating_district_geating_design": 20,
            "heating_electricity_design": 0,
            "hot_water_district_heating_design": 20,
            "hot_water_electricity_design": 0,
            "property_electricity_design": 10,
            "locally_generated_electricity_design": 10,
            "locally_generated_heating_design": 0,
            "co2_emissions_tonnes": 32.806716269999995,
            "requirment_level_gsi": 0.6,
            "green_space_index_gsi_in_operation": 0.6,
            "green_space_index_gsi_construction": 0.64,
            "green_space_index_gsi_design": 0.6,
            "green_courtyard_m2": 409,
            "green_roofs_m2": 850,
            "requirement_bicycle_parkingapartment": 2.2,
            "bicycle_parking_spacesapartment": 2.21,
            "no._bicycle_parkingspace": 159,
            "requirment_car_parkingapartment": 0.5,
            "car_parking_spacesapartment": 0.51,
            "no._of_car_parkingspace": 37,
            "requiremant_electrical_chargning_points": null,
            "chare_of_electrical_charging_points": 11,
            "no._of_electrical_charing_points": 4,
            "requirement_construction_waste_kgm2_gfa": 20,
            "construction_waste_kgm2_gfa": 39.68,
            "requirement_distance_to_vwc_m": 30,
            "distance_to_vwc_m": 29.2,
            "requirement_distance_to_recycling_room_m": 50,
            "distance_to_recycling_room_m": 29.2,
            "recycling_room_in_property": "yes",
            "requirement_materials": "All materials are controlled in an environmental assesment system",
            "building_material_assessment_system_yes_or_no": "yes",
            "number_of_deveations": 5,
            "requirements_indoor_environment": "Gold",
            "indoor_environment": "Gold"
        },
        {
            "fastighetsbeteckning": "Sonfj\u00e4llet 2",
            "developer": "Skanska",
            "phase": "Norra 2",
            "stage": "In operation",
            "no_of_appartments": 94,
            "atemp_m2": 10488,
            "national_legislation_bbr": 90,
            "requirement_level_kwhm2_atemp": 55,
            "total_energy_use_in_operation": null,
            "heating_district_heating_in_operation": null,
            "heating_electricity_in_operation": null,
            "hot_water_district_heating_in_operation": null,
            "hot_water_electricity_in_operation": null,
            "property_electricity_in_operation": null,
            "locally_generated_electricity_in_operation": null,
            "locally_generated_heating_in_operation": null,
            "total_energy_use_construction": 52,
            "heating_district_heating_construction": 25.5,
            "heating_electricity_construction": 5.4,
            "hot_water_district_heating_construction": 20,
            "hot_water_electricity_construction": 0,
            "property_electricity_construction": 9.4,
            "locally_generated_electricity_construction": 3.2,
            "locally_generated_heating_construction": 0,
            "regionally_generated_energy_construction": 0,
            "total_energy_use_design": 60,
            "heating_district_geating_design": 20,
            "heating_electricity_design": 0,
            "hot_water_district_heating_design": 20,
            "hot_water_electricity_design": 0,
            "property_electricity_design": 10,
            "locally_generated_electricity_design": 10,
            "locally_generated_heating_design": 0,
            "co2_emissions_tonnes": 36.34910064,
            "requirment_level_gsi": 0.6,
            "green_space_index_gsi_in_operation": 0.6,
            "green_space_index_gsi_construction": 0.64,
            "green_space_index_gsi_design": 0.6,
            "green_courtyard_m2": 409,
            "green_roofs_m2": 350,
            "requirement_bicycle_parkingapartment": 2.2,
            "bicycle_parking_spacesapartment": 2.45,
            "no._bicycle_parkingspace": 230,
            "requirment_car_parkingapartment": 0.5,
            "car_parking_spacesapartment": 0.45,
            "no._of_car_parkingspace": 42,
            "requiremant_electrical_chargning_points": null,
            "chare_of_electrical_charging_points": 10,
            "no._of_electrical_charing_points": 4,
            "requirement_construction_waste_kgm2_gfa": 20,
            "construction_waste_kgm2_gfa": 39.68,
            "requirement_distance_to_vwc_m": 30,
            "distance_to_vwc_m": 27.9,
            "requirement_distance_to_recycling_room_m": 50,
            "distance_to_recycling_room_m": 11.5,
            "recycling_room_in_property": "yes",
            "requirement_materials": "All materials are controlled in an environmental assesment system",
            "building_material_assessment_system_yes_or_no": "yes",
            "number_of_deveations": 5,
            "requirements_indoor_environment": "Gold",
            "indoor_environment": "Silver"
        }
    ]