var json_data = [
	{
		"id": 1,
		"full_name": "Peter Pettigrew ",
		"major": "Data Science",
		"degree": "Master in Science",
		"hobbies": "Travelling. Fashion.",
		"learning_expectation": "Learn how to visualise data in a proper way and give more useful information. By prating and learning from the teachers and other students.",
		"infoviz_skill": 5,
		"stat_skill": 7,
		"maths_skill": 8,
		"draw_skill": 6,
		"computer_skill": 8,
		"programming_skill": 8,
		"cg_skill": 6,
		"hci_skill": 4,
		"ux_skill": 7,
		"communication_skill": 10,
		"collaboration_skill": 10,
		"repo_skill": 8,
		"skill_total": 87
	},
	{
		"id": 2,
		"full_name": "Rolanda Hooch ",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Software development, reading, gaming",
		"learning_expectation": "Vast number of alternatives to present the data interactively. I want to use it for building my portfolio.",
		"infoviz_skill": 5,
		"stat_skill": 4,
		"maths_skill": 5,
		"draw_skill": 8,
		"computer_skill": 9,
		"programming_skill": 8,
		"cg_skill": 5,
		"hci_skill": 8,
		"ux_skill": 7,
		"communication_skill": 10,
		"collaboration_skill": 5,
		"repo_skill": 9,
		"skill_total": 83
	},
	{
		"id": 3,
		"full_name": "Sturgis Podmore ",
		"major": "Computer Science, Media Technology",
		"degree": "Master in Science",
		"hobbies": "Im a big data engineer (or full stack engineer) and a seasonal entrepreneur, working with industry for more than 5 years. If Im not an engineer then I would be an adventurer. I love expedition, trekking, mountaineering, skiing, last but not the least badminton. I collect adventures memories with gadgets from action cameras to drone videography but I dont publish them. Hopefully will publish it one day. The next big thing in my bucket is to learn yacht sailing this summer. ",
		"learning_expectation": "I already have a strong practical sense on modern data warehousing and rendering on Power BI. But this course will help me on the theoretical side of visualization. ",
		"infoviz_skill": 6,
		"stat_skill": 3,
		"maths_skill": 5,
		"draw_skill": 2,
		"computer_skill": 10,
		"programming_skill": 10,
		"cg_skill": 8,
		"hci_skill": 6,
		"ux_skill": 3,
		"communication_skill": 10,
		"collaboration_skill": 10,
		"repo_skill": 10,
		"skill_total": 83
	},
	{
		"id": 4,
		"full_name": "Poppy Pomfrey ",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "",
		"learning_expectation": "I would like to gather more information about how data should be structured and visualised in order to provide users with a fulfilling and insightful experience ",
		"infoviz_skill": 5,
		"stat_skill": 5,
		"maths_skill": 6,
		"draw_skill": 7,
		"computer_skill": 8,
		"programming_skill": 8,
		"cg_skill": 8,
		"hci_skill": 8,
		"ux_skill": 4,
		"communication_skill": 7,
		"collaboration_skill": 7,
		"repo_skill": 9,
		"skill_total": 82
	},
	{
		"id": 5,
		"full_name": "Harry Potter ",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "",
		"learning_expectation": "Ledsen how to visualize heavy data in a intuitive way ",
		"infoviz_skill": 7,
		"stat_skill": 2,
		"maths_skill": 4,
		"draw_skill": 10,
		"computer_skill": 8,
		"programming_skill": 5,
		"cg_skill": 4,
		"hci_skill": 8,
		"ux_skill": 9,
		"communication_skill": 8,
		"collaboration_skill": 8,
		"repo_skill": 7,
		"skill_total": 80
	},
	{
		"id": 6,
		"full_name": "Graham Montague",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "I finished my bachelors a couple of years ago and started working right away in the industry as a UI Engineer consultant focusing mainly on web technologies. Ive also taken on some jobs before getting my degree but most were freelancing or volunteering. Right now Im interested in meeting new people and sharpening my HCI-related skills. Some of my hobbies include playing music, coding, gaming, and reading.",
		"learning_expectation": "Best practices when dealing with data visualization, do, donts, etc. Common tools, or at least the notion that they exist, to use professionally. Practical knowledge that can be applied as soon as the course is over.",
		"infoviz_skill": 3,
		"stat_skill": 5,
		"maths_skill": 7,
		"draw_skill": 3,
		"computer_skill": 9,
		"programming_skill": 8,
		"cg_skill": 3,
		"hci_skill": 5,
		"ux_skill": 7,
		"communication_skill": 8,
		"collaboration_skill": 10,
		"repo_skill": 9,
		"skill_total": 77
	},
	{
		"id": 7,
		"full_name": "Pansy Parkinson",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "",
		"learning_expectation": "Representing data in a way that gives a good overview of it. Will probably be useful to know almost anywhere as so much depends on studying all the data collected.",
		"infoviz_skill": 7,
		"stat_skill": 4,
		"maths_skill": 4,
		"draw_skill": 7,
		"computer_skill": 8,
		"programming_skill": 8,
		"cg_skill": 6,
		"hci_skill": 7,
		"ux_skill": 4,
		"communication_skill": 7,
		"collaboration_skill": 8,
		"repo_skill": 7,
		"skill_total": 77
	},
	{
		"id": 8,
		"full_name": "Millicent Bulstrode",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "",
		"learning_expectation": "I expect that Ill get knowledge about what different visualisation tools that exist as well as what one should think about when visualising data. Hopefully in my future work.",
		"infoviz_skill": 2,
		"stat_skill": 3,
		"maths_skill": 10,
		"draw_skill": 8,
		"computer_skill": 10,
		"programming_skill": 7,
		"cg_skill": 2,
		"hci_skill": 6,
		"ux_skill": 2,
		"communication_skill": 10,
		"collaboration_skill": 7,
		"repo_skill": 8,
		"skill_total": 75
	},
	{
		"id": 9,
		"full_name": "Draco Malfoy",
		"major": "Computer Science, Human_Computer Interaction",
		"degree": "Master in Science",
		"hobbies": "Computer games, reading, netflix, watching Twitch streams, beer",
		"learning_expectation": "To learn tools to display information further than in an infograph.",
		"infoviz_skill": 4,
		"stat_skill": 1,
		"maths_skill": 2,
		"draw_skill": 1,
		"computer_skill": 9,
		"programming_skill": 9,
		"cg_skill": 3,
		"hci_skill": 8,
		"ux_skill": 9,
		"communication_skill": 9,
		"collaboration_skill": 10,
		"repo_skill": 10,
		"skill_total": 75
	},
	{
		"id": 10,
		"full_name": "Vincent Crabbe",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "I really enjoy my studies and Im also running a digital agency besides the studies from 2,5 years back. When I dont enjoy studying or working I like to travel, meet new people, have beers with friends and be with my family.",
		"learning_expectation": "Possibly testing out working with new technologies and being able to motivate different design choices when it comes to visualizing data. The basics of what visualizations works best in what situations etc.",
		"infoviz_skill": 5,
		"stat_skill": 2,
		"maths_skill": 2,
		"draw_skill": 7,
		"computer_skill": 9,
		"programming_skill": 6,
		"cg_skill": 2,
		"hci_skill": 6,
		"ux_skill": 7,
		"communication_skill": 10,
		"collaboration_skill": 9,
		"repo_skill": 9,
		"skill_total": 74
	},
	{
		"id": 11,
		"full_name": "Neville Longbottom",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Games.",
		"learning_expectation": "How to create nice visuals using programming. Expect to use it to create nice products in the future.",
		"infoviz_skill": 3,
		"stat_skill": 5,
		"maths_skill": 5,
		"draw_skill": 3,
		"computer_skill": 8,
		"programming_skill": 6,
		"cg_skill": 3,
		"hci_skill": 5,
		"ux_skill": 7,
		"communication_skill": 10,
		"collaboration_skill": 10,
		"repo_skill": 9,
		"skill_total": 74
	},
	{
		"id": 12,
		"full_name": "Bathilda Bagshot ",
		"major": "Engineering Physics",
		"degree": "Bachelor in Science",
		"hobbies": "I am an Erasmus exchange student from Istanbul Technical University. I am studying Engineering Physics but I have a huge interest in programming and data science. I am taking half of my courses in machine learning, data science and artificial intelligence fields. I am familiar with Photoshop and Illustrator, done some poster works with them in the past. I like minimalist designs and making them avant-garde.",
		"learning_expectation": "Representing data in a meaningful way and making understandable for everyone. Also the methods and concepts for different types of data structres.",
		"infoviz_skill": 6,
		"stat_skill": 5,
		"maths_skill": 5,
		"draw_skill": 3,
		"computer_skill": 10,
		"programming_skill": 7,
		"cg_skill": 4,
		"hci_skill": 6,
		"ux_skill": 4,
		"communication_skill": 10,
		"collaboration_skill": 7,
		"repo_skill": 5,
		"skill_total": 72
	},
	{
		"id": 13,
		"full_name": "Amycus Carrow",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Rendering algorithms, game engine development and utility",
		"learning_expectation": "Some modern visualization methods, use tools or on web pages",
		"infoviz_skill": 5,
		"stat_skill": 6,
		"maths_skill": 5,
		"draw_skill": 6,
		"computer_skill": 9,
		"programming_skill": 7,
		"cg_skill": 8,
		"hci_skill": 2,
		"ux_skill": 1,
		"communication_skill": 7,
		"collaboration_skill": 7,
		"repo_skill": 9,
		"skill_total": 72
	},
	{
		"id": 14,
		"full_name": "Reginald Cattermole",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Social interaction, Swimming, Video games, Programming, food. ",
		"learning_expectation": "There have been several instances in different courses that teaches about the ability to acquire and structure data, but from the course, I wish to learn the ability to actually present it in a manner that is both intuitive and efficient. I think it is a very good skill to have in most fields within computer science today, since you will very likely be dealing with a lot of abstraction. Abstracting away unnecessary information while still keeping it wholesome is a very good ability to have. ",
		"infoviz_skill": 4,
		"stat_skill": 5,
		"maths_skill": 7,
		"draw_skill": 3,
		"computer_skill": 9,
		"programming_skill": 9,
		"cg_skill": 1,
		"hci_skill": 4,
		"ux_skill": 2,
		"communication_skill": 10,
		"collaboration_skill": 7,
		"repo_skill": 10,
		"skill_total": 71
	},
	{
		"id": 15,
		"full_name": "Igor Karkaroff ",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "",
		"learning_expectation": "The theory and methods to develop a information chart",
		"infoviz_skill": 7,
		"stat_skill": 6,
		"maths_skill": 6,
		"draw_skill": 3,
		"computer_skill": 7,
		"programming_skill": 7,
		"cg_skill": 4,
		"hci_skill": 6,
		"ux_skill": 6,
		"communication_skill": 7,
		"collaboration_skill": 6,
		"repo_skill": 6,
		"skill_total": 71
	},
	{
		"id": 16,
		"full_name": "Colin Creevey",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "UX design, Wireframing, Programming (C, Obj-C, C++, Python), Gaming, Reading up on tech news",
		"learning_expectation": "I wish to learn how to effectively visualise abstract data so as create modular interfaces that users can use to gather meaningful insights. This would greatly hep me with my current line of work as UX consultant ",
		"infoviz_skill": 7,
		"stat_skill": 3,
		"maths_skill": 6,
		"draw_skill": 8,
		"computer_skill": 10,
		"programming_skill": 8,
		"cg_skill": 2,
		"hci_skill": 6,
		"ux_skill": 4,
		"communication_skill": 5,
		"collaboration_skill": 2,
		"repo_skill": 9,
		"skill_total": 70
	},
	{
		"id": 17,
		"full_name": "Bellatrix Lestrange",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Creating cool shit, mostly on some sort of a computer.",
		"learning_expectation": "Ways of displaying information in a way that makes it easy to take in, for both questions",
		"infoviz_skill": 3,
		"stat_skill": 5,
		"maths_skill": 6,
		"draw_skill": 3,
		"computer_skill": 9,
		"programming_skill": 7,
		"cg_skill": 5,
		"hci_skill": 4,
		"ux_skill": 5,
		"communication_skill": 7,
		"collaboration_skill": 8,
		"repo_skill": 8,
		"skill_total": 70
	},
	{
		"id": 18,
		"full_name": "Phineas Nigellus Black",
		"major": "Human_Computer Interaction",
		"degree": "Master in Science",
		"hobbies": "Film, music videos, skiing",
		"learning_expectation": "I don’t really know yet.",
		"infoviz_skill": 4,
		"stat_skill": 5,
		"maths_skill": 6,
		"draw_skill": 7,
		"computer_skill": 6,
		"programming_skill": 3,
		"cg_skill": 2,
		"hci_skill": 5,
		"ux_skill": 7,
		"communication_skill": 10,
		"collaboration_skill": 8,
		"repo_skill": 6,
		"skill_total": 69
	},
	{
		"id": 19,
		"full_name": "Hermione Granger",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Drawing",
		"learning_expectation": "I want to be able to have different theories and methods I can evaluate between when choosing visualization technique in the future. For an example, how to visualize three data variables in a 2D plot.",
		"infoviz_skill": 2,
		"stat_skill": 2,
		"maths_skill": 4,
		"draw_skill": 8,
		"computer_skill": 9,
		"programming_skill": 8,
		"cg_skill": 2,
		"hci_skill": 6,
		"ux_skill": 4,
		"communication_skill": 7,
		"collaboration_skill": 8,
		"repo_skill": 9,
		"skill_total": 69
	},
	{
		"id": 20,
		"full_name": "Ernie Macmillan",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "Sports of all kinds, computer games, programming (i suppose?)",
		"learning_expectation": "General good practices in info vis.Tools and utilities.Want to do something fun and creative where i put my old and newly aquired skills to use.Wanna do an awesome project to put in my portfolio.",
		"infoviz_skill": 3,
		"stat_skill": 6,
		"maths_skill": 4,
		"draw_skill": 2,
		"computer_skill": 8,
		"programming_skill": 5,
		"cg_skill": 2,
		"hci_skill": 7,
		"ux_skill": 7,
		"communication_skill": 10,
		"collaboration_skill": 9,
		"repo_skill": 6,
		"skill_total": 69
	},
	{
		"id": 21,
		"full_name": "Terry Boot",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "Music, dance",
		"learning_expectation": "How to, in a efficient way, visualize data. How to do that interactively rather than relying on things like infographics where the creator chooses what data to show instead of the user.",
		"infoviz_skill": 7,
		"stat_skill": 6,
		"maths_skill": 5,
		"draw_skill": 4,
		"computer_skill": 10,
		"programming_skill": 8,
		"cg_skill": 1,
		"hci_skill": 3,
		"ux_skill": 2,
		"communication_skill": 10,
		"collaboration_skill": 3,
		"repo_skill": 8,
		"skill_total": 67
	},
	{
		"id": 22,
		"full_name": "Charity Burbage",
		"major": "Media Technology",
		"degree": "Master in Computer Science with specialization in Interactive Media Technology",
		"hobbies": "Im big into football. In the Swedish league Allsvenskan I follow AIK, but I also follow English club Liverpool FC tirelessly. About a year ago, I also picked up playing the guitar which has turned out to be a great hobby for me. ",
		"learning_expectation": "To transform big datasets retrieved from somewhere on the web into some sort of visualization of the dataset. ",
		"infoviz_skill": 2,
		"stat_skill": 4,
		"maths_skill": 7,
		"draw_skill": 3,
		"computer_skill": 7,
		"programming_skill": 6,
		"cg_skill": 2,
		"hci_skill": 5,
		"ux_skill": 6,
		"communication_skill": 9,
		"collaboration_skill": 10,
		"repo_skill": 6,
		"skill_total": 67
	},
	{
		"id": 23,
		"full_name": "Xenophilius Lovegood ",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Video games and music",
		"learning_expectation": "I expect to learn about how to visualize information in a way that is easy to understand",
		"infoviz_skill": 5,
		"stat_skill": 3,
		"maths_skill": 3,
		"draw_skill": 7,
		"computer_skill": 9,
		"programming_skill": 7,
		"cg_skill": 3,
		"hci_skill": 6,
		"ux_skill": 7,
		"communication_skill": 7,
		"collaboration_skill": 5,
		"repo_skill": 4,
		"skill_total": 66
	},
	{
		"id": 24,
		"full_name": "Mary Cattermole ",
		"major": "Computer Science, Business Administration",
		"degree": "Master in Science",
		"hobbies": "Travel",
		"learning_expectation": "I want to learn the way to be D3 super master, and to go through challenging project with my friends ovvvvernight!",
		"infoviz_skill": 8,
		"stat_skill": 8,
		"maths_skill": 7,
		"draw_skill": 5,
		"computer_skill": 9,
		"programming_skill": 8,
		"cg_skill": 2,
		"hci_skill": 1,
		"ux_skill": 2,
		"communication_skill": 5,
		"collaboration_skill": 2,
		"repo_skill": 8,
		"skill_total": 65
	},
	{
		"id": 25,
		"full_name": "Fleur Delacour ",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "Im interested in graphics, UX-UI, web dev ",
		"learning_expectation": "I expect to learn how to take seemingly ordinary datasets and through visualisation make them extraordinary and insightful.",
		"infoviz_skill": 4,
		"stat_skill": 3,
		"maths_skill": 2,
		"draw_skill": 7,
		"computer_skill": 10,
		"programming_skill": 3,
		"cg_skill": 1,
		"hci_skill": 5,
		"ux_skill": 6,
		"communication_skill": 9,
		"collaboration_skill": 9,
		"repo_skill": 5,
		"skill_total": 64
	},
	{
		"id": 26,
		"full_name": "Viktor Krum",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Sports and video games",
		"learning_expectation": "I want to learn how to properly visualize information. I might want to work with something about it or use the knowledge in my own projects, such as a website.",
		"infoviz_skill": 6,
		"stat_skill": 4,
		"maths_skill": 4,
		"draw_skill": 4,
		"computer_skill": 8,
		"programming_skill": 4,
		"cg_skill": 3,
		"hci_skill": 4,
		"ux_skill": 4,
		"communication_skill": 10,
		"collaboration_skill": 6,
		"repo_skill": 7,
		"skill_total": 64
	},
	{
		"id": 27,
		"full_name": "Irma Pince",
		"major": "Computer Science, Human_Computer Interaction",
		"degree": "Master in Science",
		"hobbies": "I like to work with more frontend-oriented technology, and in particular with solutions where I get to understand how to create something that has a high degree of usability(i.e. my interest in HCI in general).In terms of other hobbies, I have a keen interest in films as well as football. ",
		"learning_expectation": "I am interested in learning more about information visualization as I think the importance of it is growing rapidly as more and more data is available.I expect to get more hands-on experience with creating visuals related to information visualization. Im not sure if there are any specific good-practices(I dont expect it to) but I am eager to see what research material on the topic also says.I believe I might be able to use what Ive learned in a potential future career choice. For instance if I want to learn more about Business Intelligence this could be valuable. ",
		"infoviz_skill": 1,
		"stat_skill": 5,
		"maths_skill": 7,
		"draw_skill": 2,
		"computer_skill": 9,
		"programming_skill": 6,
		"cg_skill": 1,
		"hci_skill": 6,
		"ux_skill": 7,
		"communication_skill": 7,
		"collaboration_skill": 8,
		"repo_skill": 4,
		"skill_total": 63
	},
	{
		"id": 28,
		"full_name": "Michael Corner",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "Music, sports, photography, games",
		"learning_expectation": "How to effectively display information and make it look interesting while being interactive.",
		"infoviz_skill": 5,
		"stat_skill": 4,
		"maths_skill": 6,
		"draw_skill": 5,
		"computer_skill": 7,
		"programming_skill": 5,
		"cg_skill": 4,
		"hci_skill": 4,
		"ux_skill": 4,
		"communication_skill": 6,
		"collaboration_skill": 6,
		"repo_skill": 6,
		"skill_total": 62
	},
	{
		"id": 29,
		"full_name": "Marcus Flint",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Programming, video games, anything computer-related ",
		"learning_expectation": "I expect to learn how to present different type of data in the best way possible",
		"infoviz_skill": 6,
		"stat_skill": 2,
		"maths_skill": 2,
		"draw_skill": 5,
		"computer_skill": 8,
		"programming_skill": 7,
		"cg_skill": 8,
		"hci_skill": 6,
		"ux_skill": 2,
		"communication_skill": 5,
		"collaboration_skill": 5,
		"repo_skill": 6,
		"skill_total": 62
	},
	{
		"id": 30,
		"full_name": "Filius Flitwick ",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "I love music. I play a few instruments. Photography and film as well. Any creative channels",
		"learning_expectation": "I expect to learn how to effectively communicate data. Improve my design  process and discover more technologies.",
		"infoviz_skill": 3,
		"stat_skill": 5,
		"maths_skill": 6,
		"draw_skill": 7,
		"computer_skill": 9,
		"programming_skill": 1,
		"cg_skill": 1,
		"hci_skill": 1,
		"ux_skill": 7,
		"communication_skill": 7,
		"collaboration_skill": 9,
		"repo_skill": 4,
		"skill_total": 60
	},
	{
		"id": 31,
		"full_name": "Theodore Nott",
		"major": "Human_Computer Interaction, Media Technology",
		"degree": "Master in interactive media technology",
		"hobbies": "I like art and paint a lot. I have worked as a UX designer and love to create beautiful things such as logos and prototypes. I do also like front-end programming.",
		"learning_expectation": "I love rhetoric and being able to influence people. I expect to be able to influence people to an even greater level with the help of visualization.",
		"infoviz_skill": 1,
		"stat_skill": 1,
		"maths_skill": 5,
		"draw_skill": 10,
		"computer_skill": 8,
		"programming_skill": 2,
		"cg_skill": 1,
		"hci_skill": 3,
		"ux_skill": 7,
		"communication_skill": 10,
		"collaboration_skill": 10,
		"repo_skill": 1,
		"skill_total": 59
	},
	{
		"id": 32,
		"full_name": "Ludo Bagman ",
		"major": "Machine Learning",
		"degree": "Master in Science",
		"hobbies": "Going to the gym",
		"learning_expectation": "I wish to learn and be proficient at relevant and useful visualization tools and methods in order to be able to create vizualisations in projects and future work. ",
		"infoviz_skill": 1,
		"stat_skill": 5,
		"maths_skill": 5,
		"draw_skill": 1,
		"computer_skill": 7,
		"programming_skill": 8,
		"cg_skill": 3,
		"hci_skill": 2,
		"ux_skill": 1,
		"communication_skill": 10,
		"collaboration_skill": 8,
		"repo_skill": 7,
		"skill_total": 58
	},
	{
		"id": 33,
		"full_name": "Alecto Carrow",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "Computer games, working out, padle",
		"learning_expectation": "How to handle and use big amounts of data to explain things.",
		"infoviz_skill": 1,
		"stat_skill": 3,
		"maths_skill": 6,
		"draw_skill": 3,
		"computer_skill": 7,
		"programming_skill": 5,
		"cg_skill": 1,
		"hci_skill": 4,
		"ux_skill": 4,
		"communication_skill": 8,
		"collaboration_skill": 9,
		"repo_skill": 7,
		"skill_total": 58
	},
	{
		"id": 34,
		"full_name": "Cormac McLaggen",
		"major": "Data Science",
		"degree": "Master in Science",
		"hobbies": "Art has always fascinated me  though I am not an artist but I feel that creative minds always look at things in a very different way. Looking at the data and visualizing it in a unique way is interesting as well as exciting . I love to cook .It is something that makes me happy . I become a creative person whenever i cook.",
		"learning_expectation": "I expect to see data in a different way .I am pretty excited about this course  and its my area of interest .I feel this course will help me a lot .",
		"infoviz_skill": 4,
		"stat_skill": 5,
		"maths_skill": 4,
		"draw_skill": 6,
		"computer_skill": 5,
		"programming_skill": 6,
		"cg_skill": 4,
		"hci_skill": 2,
		"ux_skill": 5,
		"communication_skill": 7,
		"collaboration_skill": 6,
		"repo_skill": 4,
		"skill_total": 58
	},
	{
		"id": 35,
		"full_name": "Garrick Ollivander ",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "",
		"learning_expectation": "Honestly i expect to learn how to make computer graphics that look cool.",
		"infoviz_skill": 3,
		"stat_skill": 3,
		"maths_skill": 4,
		"draw_skill": 3,
		"computer_skill": 9,
		"programming_skill": 8,
		"cg_skill": 5,
		"hci_skill": 5,
		"ux_skill": 3,
		"communication_skill": 7,
		"collaboration_skill": 7,
		"repo_skill": 1,
		"skill_total": 58
	},
	{
		"id": 36,
		"full_name": "Albus Dumbledore",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "I am a musician beside my studies at KTH.",
		"learning_expectation": "I hope to learn more about efficient visualization methods and then practice these in the projects. Im not exactly sure how Ill use the knowledge, maybe in my future profession?",
		"infoviz_skill": 3,
		"stat_skill": 6,
		"maths_skill": 6,
		"draw_skill": 3,
		"computer_skill": 6,
		"programming_skill": 4,
		"cg_skill": 2,
		"hci_skill": 3,
		"ux_skill": 4,
		"communication_skill": 6,
		"collaboration_skill": 8,
		"repo_skill": 6,
		"skill_total": 57
	},
	{
		"id": 37,
		"full_name": "Seamus Finnigan",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Programming, Rocket League, Music",
		"learning_expectation": "Cool visualizations",
		"infoviz_skill": 1,
		"stat_skill": 3,
		"maths_skill": 5,
		"draw_skill": 1,
		"computer_skill": 9,
		"programming_skill": 7,
		"cg_skill": 8,
		"hci_skill": 3,
		"ux_skill": 2,
		"communication_skill": 1,
		"collaboration_skill": 9,
		"repo_skill": 8,
		"skill_total": 57
	},
	{
		"id": 38,
		"full_name": "Silvanus Kettleburn ",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "I have a BFA in electronic media, so I enjoy art a lot: Exhibitions, paintings, drawings and all the other things in that world. I also like to exercise, I ride my bicycle (not in the snow), do indoor-rowing and basic exercise.  Used to work in a huge library and learned to love old books and manuscripts with forgotten stories. I have always liked programming and therefore decided to study my masters in order to explore more and improve my skills. ",
		"learning_expectation": "I want know get the knowledge to take proper decisions either collecting data and visualizing it. I would prefer to practice it and do stuff from little to big projects. I would like use it in art installations, graphic design and web pages initially, but I would like to go beyond that. ",
		"infoviz_skill": 4,
		"stat_skill": 2,
		"maths_skill": 2,
		"draw_skill": 9,
		"computer_skill": 8,
		"programming_skill": 3,
		"cg_skill": 2,
		"hci_skill": 2,
		"ux_skill": 3,
		"communication_skill": 9,
		"collaboration_skill": 8,
		"repo_skill": 5,
		"skill_total": 57
	},
	{
		"id": 39,
		"full_name": "Godric Gryffindor ",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Programming, Music/Guitar, Gaming",
		"learning_expectation": "I expect to learn how to visualize data in an intriguing and user-friendly manner. This is a skill i aim to use in my future work and projects when coding websites and GUIs",
		"infoviz_skill": 2,
		"stat_skill": 5,
		"maths_skill": 7,
		"draw_skill": 3,
		"computer_skill": 4,
		"programming_skill": 5,
		"cg_skill": 3,
		"hci_skill": 3,
		"ux_skill": 1,
		"communication_skill": 10,
		"collaboration_skill": 8,
		"repo_skill": 5,
		"skill_total": 56
	},
	{
		"id": 40,
		"full_name": "Penelope Clearwater ",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "I am interested in all things visual. Love movies and especially video games. Got really interested in augmented reality from the Multimodal Interactions. Like web-developing in javascript with frameworks such as React and Angular. Excited to work with D3.js. ",
		"learning_expectation": "I expect to be an expert in D3.js and generally get a better idea and foundation on visualizing information. Like, if I get a dataset, hopefully I will have a better mindset on how to visualize it.",
		"infoviz_skill": 4,
		"stat_skill": 2,
		"maths_skill": 3,
		"draw_skill": 3,
		"computer_skill": 8,
		"programming_skill": 3,
		"cg_skill": 1,
		"hci_skill": 5,
		"ux_skill": 2,
		"communication_skill": 9,
		"collaboration_skill": 8,
		"repo_skill": 7,
		"skill_total": 55
	},
	{
		"id": 41,
		"full_name": "Remus Lupin",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Working out at the gym and playing video games. ",
		"learning_expectation": "More about java script and its visual frameworks such as D3.js and also how to present data in an intuitive manner. Maybe at a future workplace. ",
		"infoviz_skill": 3,
		"stat_skill": 4,
		"maths_skill": 4,
		"draw_skill": 4,
		"computer_skill": 7,
		"programming_skill": 5,
		"cg_skill": 1,
		"hci_skill": 3,
		"ux_skill": 2,
		"communication_skill": 8,
		"collaboration_skill": 8,
		"repo_skill": 6,
		"skill_total": 55
	},
	{
		"id": 42,
		"full_name": "Cuthbert Binns",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "I enjoy doodling and bullet journaling, dancing and playing the badminton.",
		"learning_expectation": "I want to acquire the skills of making informative and interactive visualizations, and would also like to add some information visualization projects to my portfolio. ",
		"infoviz_skill": 5,
		"stat_skill": 5,
		"maths_skill": 5,
		"draw_skill": 3,
		"computer_skill": 7,
		"programming_skill": 7,
		"cg_skill": 2,
		"hci_skill": 3,
		"ux_skill": 1,
		"communication_skill": 4,
		"collaboration_skill": 5,
		"repo_skill": 7,
		"skill_total": 54
	},
	{
		"id": 43,
		"full_name": "Lavender Brown",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "I am interested in sports (preferably hockey followed by soccer) and music.",
		"learning_expectation": "I expect to learn how to use data and present it in a way so that it makes sense to other people.",
		"infoviz_skill": 2,
		"stat_skill": 4,
		"maths_skill": 5,
		"draw_skill": 2,
		"computer_skill": 7,
		"programming_skill": 3,
		"cg_skill": 1,
		"hci_skill": 3,
		"ux_skill": 4,
		"communication_skill": 10,
		"collaboration_skill": 9,
		"repo_skill": 4,
		"skill_total": 54
	},
	{
		"id": 44,
		"full_name": "Gellert Grindelwald ",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Cooking and sports.",
		"learning_expectation": "How to present data in a Clear/fun way",
		"infoviz_skill": 5,
		"stat_skill": 3,
		"maths_skill": 4,
		"draw_skill": 6,
		"computer_skill": 6,
		"programming_skill": 3,
		"cg_skill": 1,
		"hci_skill": 2,
		"ux_skill": 5,
		"communication_skill": 7,
		"collaboration_skill": 8,
		"repo_skill": 4,
		"skill_total": 54
	},
	{
		"id": 45,
		"full_name": "Susan Bones ",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Football, Youtube",
		"learning_expectation": "I would like to create clear and fancy visulaizations of the data that I analyse and process. So I expect to learn how to be clear and efficient.",
		"infoviz_skill": 2,
		"stat_skill": 6,
		"maths_skill": 8,
		"draw_skill": 2,
		"computer_skill": 6,
		"programming_skill": 4,
		"cg_skill": 2,
		"hci_skill": 2,
		"ux_skill": 3,
		"communication_skill": 7,
		"collaboration_skill": 6,
		"repo_skill": 5,
		"skill_total": 53
	},
	{
		"id": 46,
		"full_name": "Rubeus Hagrid ",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Photography, politics, news",
		"learning_expectation": "How to create context from raw data, highlighting hidden connections, making information more usable and understandable. ",
		"infoviz_skill": 3,
		"stat_skill": 4,
		"maths_skill": 4,
		"draw_skill": 1,
		"computer_skill": 7,
		"programming_skill": 6,
		"cg_skill": 1,
		"hci_skill": 3,
		"ux_skill": 2,
		"communication_skill": 8,
		"collaboration_skill": 6,
		"repo_skill": 7,
		"skill_total": 52
	},
	{
		"id": 47,
		"full_name": "Sirius Black",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Im interested in machine learning, graphics and visualization. I do also make computer games as a hobby.",
		"learning_expectation": "I hope to somehow be able to apply it in conjunction with machine learning (perhaps using it to visualize machine learning data or decision making). Mostly though, it just seemed like a generally useful skill to have.",
		"infoviz_skill": 2,
		"stat_skill": 2,
		"maths_skill": 4,
		"draw_skill": 8,
		"computer_skill": 7,
		"programming_skill": 5,
		"cg_skill": 4,
		"hci_skill": 3,
		"ux_skill": 2,
		"communication_skill": 4,
		"collaboration_skill": 5,
		"repo_skill": 4,
		"skill_total": 50
	},
	{
		"id": 48,
		"full_name": "Helga Hufflepuff",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "Any type of development interests me a lot. I also love teaching others and making products which other people appreciate",
		"learning_expectation": "How to make pretty information visualizations which conveys information in a really clear way to anyone, it should also be fun to interact with. Today I have no idea how to do anything close to this, so any step in this direction is a welcomed one!",
		"infoviz_skill": 1,
		"stat_skill": 3,
		"maths_skill": 5,
		"draw_skill": 3,
		"computer_skill": 7,
		"programming_skill": 4,
		"cg_skill": 1,
		"hci_skill": 3,
		"ux_skill": 4,
		"communication_skill": 9,
		"collaboration_skill": 4,
		"repo_skill": 6,
		"skill_total": 50
	},
	{
		"id": 49,
		"full_name": "Amos Diggory",
		"major": "Computer Science",
		"degree": "Master in Science",
		"hobbies": "Training ",
		"learning_expectation": "Im expecting to learn in what way you should present data and the different good ways you can present data. ",
		"infoviz_skill": 2,
		"stat_skill": 4,
		"maths_skill": 5,
		"draw_skill": 3,
		"computer_skill": 7,
		"programming_skill": 4,
		"cg_skill": 1,
		"hci_skill": 2,
		"ux_skill": 1,
		"communication_skill": 6,
		"collaboration_skill": 7,
		"repo_skill": 7,
		"skill_total": 49
	},
	{
		"id": 50,
		"full_name": "Minerva McGonagall",
		"major": "Human_Computer Interaction, Media Technology",
		"degree": "Master in Science",
		"hobbies": "I like to create and design pretty things",
		"learning_expectation": "How to visualise things in a better way and also new frameworks and tools for doing so",
		"infoviz_skill": 3,
		"stat_skill": 1,
		"maths_skill": 4,
		"draw_skill": 6,
		"computer_skill": 7,
		"programming_skill": 2,
		"cg_skill": 1,
		"hci_skill": 4,
		"ux_skill": 5,
		"communication_skill": 9,
		"collaboration_skill": 6,
		"repo_skill": 1,
		"skill_total": 49
	},
	{
		"id": 51,
		"full_name": "Antioch Peverell",
		"major": "Computer Science, Media Technology, Mathematics, Statistics, Machine Learning",
		"degree": "Master in Science",
		"hobbies": "I love to watch and play football. I also like video games and how they are made. ",
		"learning_expectation": "Since im always working with data, im really interested in the way of presenting it. With this course, I hope to be able to interpret some graphs more easily and to make them.",
		"infoviz_skill": 1,
		"stat_skill": 6,
		"maths_skill": 6,
		"draw_skill": 2,
		"computer_skill": 8,
		"programming_skill": 3,
		"cg_skill": 1,
		"hci_skill": 2,
		"ux_skill": 3,
		"communication_skill": 6,
		"collaboration_skill": 6,
		"repo_skill": 5,
		"skill_total": 49
	},
	{
		"id": 52,
		"full_name": "Cornelius Fudge",
		"major": "Systems,  Robotics and Control",
		"degree": "Master in Science",
		"hobbies": "My educational interests are mainly centered around autonomous systems. I like the idea of robots autonomously interacting with their environment. Thus, areas such as computer vision and machine learning is what really interests me. Apart from that I really enjoy spending time in nature and taking photos. I also enjoy doing a lot of sports and am constantly trying to improve my Swedish..",
		"learning_expectation": "I usually work with a lot of data that is at times really difficult to comprehend due to a lack of intuitive insights into what the data represents. I expect to learn something about ways to visualize data in a way that it allows for an intuitive understanding of what the data represents even in complicated applications. I expect to use the knowledge from this course in presentations and projects centered around robots that will allow me to comprehensively visualize the complex mathematical stuff going on in the background.",
		"infoviz_skill": 2,
		"stat_skill": 6,
		"maths_skill": 6,
		"draw_skill": 2,
		"computer_skill": 4,
		"programming_skill": 4,
		"cg_skill": 2,
		"hci_skill": 3,
		"ux_skill": 1,
		"communication_skill": 6,
		"collaboration_skill": 6,
		"repo_skill": 5,
		"skill_total": 47
	},
	{
		"id": 53,
		"full_name": "Hannah Abbott ",
		"major": "Computer Science",
		"degree": "Bachelor in Science",
		"hobbies": "Im interested in visualization because it allows us to gain insight from complex and large data sets. I like skiing, hiking, and music.",
		"learning_expectation": "Be able to tell a story through data driven document.",
		"infoviz_skill": 4,
		"stat_skill": 3,
		"maths_skill": 6,
		"draw_skill": 2,
		"computer_skill": 6,
		"programming_skill": 5,
		"cg_skill": 3,
		"hci_skill": 4,
		"ux_skill": 1,
		"communication_skill": 4,
		"collaboration_skill": 3,
		"repo_skill": 5,
		"skill_total": 46
	},
	{
		"id": 54,
		"full_name": "Katie Bell ",
		"major": "Computer Science, Media Technology",
		"degree": "Master in Science",
		"hobbies": "Games, art",
		"learning_expectation": "I expect to learn how to design an interactive graphics s.t. it is easy for the user to understand and guide through. I expect to use it to present data to the user e.g. game stats, food choices and interactive museums.",
		"infoviz_skill": 2,
		"stat_skill": 2,
		"maths_skill": 4,
		"draw_skill": 7,
		"computer_skill": 6,
		"programming_skill": 3,
		"cg_skill": 2,
		"hci_skill": 2,
		"ux_skill": 4,
		"communication_skill": 7,
		"collaboration_skill": 5,
		"repo_skill": 2,
		"skill_total": 46
	},
	{
		"id": 55,
		"full_name": "Amelia Bones ",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "Gym, baking cakes, socialize with friends.",
		"learning_expectation": "I expect to learn how to visualize information in good and handy ways. Hopefully I can use my new learnings in some other projects and eventually in my future career.",
		"infoviz_skill": 3,
		"stat_skill": 2,
		"maths_skill": 5,
		"draw_skill": 5,
		"computer_skill": 6,
		"programming_skill": 2,
		"cg_skill": 1,
		"hci_skill": 1,
		"ux_skill": 3,
		"communication_skill": 8,
		"collaboration_skill": 7,
		"repo_skill": 3,
		"skill_total": 46
	},
	{
		"id": 56,
		"full_name": "Frank Bryce",
		"major": "Media Technology",
		"degree": "Master in Science",
		"hobbies": "Im a media technology student with interests in web design/development, video, photography and graphics. In my spare time I like spending time learning graphic design, motion graphics and to become a better web designer/developer. Moreover I enjoy photography, sports and watching movies. ",
		"learning_expectation": "To learn about theories and techniques behind information visualization to be able to create interactive programs for presenting data. I think this knowledge can be useful in many different situations i.e to analyze statistics and keep track of sales, especially today with big data.",
		"infoviz_skill": 2,
		"stat_skill": 2,
		"maths_skill": 4,
		"draw_skill": 2,
		"computer_skill": 6,
		"programming_skill": 3,
		"cg_skill": 1,
		"hci_skill": 2,
		"ux_skill": 3,
		"communication_skill": 7,
		"collaboration_skill": 3,
		"repo_skill": 4,
		"skill_total": 39
	},
	{
		"id": 57,
		"full_name": "Cho Chang ",
		"major": "Statistics, Systems Engineering and Management",
		"degree": "Bachelor in Engineering (in my home institute)",
		"hobbies": "Listening to music",
		"learning_expectation": "Learn the method of presenting ideas to end users when giving out presentation.",
		"infoviz_skill": 2,
		"stat_skill": 3,
		"maths_skill": 4,
		"draw_skill": 1,
		"computer_skill": 3,
		"programming_skill": 1,
		"cg_skill": 1,
		"hci_skill": 2,
		"ux_skill": 3,
		"communication_skill": 9,
		"collaboration_skill": 9,
		"repo_skill": 1,
		"skill_total": 39
	}
]